# Generated by Django 4.2.5 on 2023-11-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_subcategory_elctronics_subcat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='elctronics_subcat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='snicker_subcat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
