# Generated by Django 4.2.5 on 2023-11-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_product_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='elctronics_subcat',
            new_name='brand_subcat',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='snicker_subcat',
            new_name='main_subcat',
        ),
    ]
