# Generated by Django 4.2.5 on 2023-11-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_elctronics_subcat_subcategory_brand_subcat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNISEX')], max_length=50, null=True),
        ),
    ]
