# Generated by Django 4.2.5 on 2023-11-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_variation_product_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='variation',
        ),
    ]
